version: "3.9"
services:
  postgres_dev:
    image: postgres:16
    container_name: postgres_dev
    environment:
      POSTGRES_DB: produtos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d produtos_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  postgres_test:
    image: postgres:16
    container_name: postgres_test
    environment:
      POSTGRES_DB: produtos_test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d produtos_test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: